/*
 * Site-level identity constants.
 *
 * These are the values that are neither chrome strings (src/i18n/ui.ts) nor
 * page copy (src/content). They appear in structured data, the contact
 * section and the footer, so they live in exactly one place.
 *
 * The GoatCounter code is public by design — it is sent from the browser — so
 * committing it is not a leak. Until it is set, the analytics tag is simply
 * not rendered; see BaseLayout.astro.
 */
export const siteConfig = {
  name: 'Adam Ligocki',
  email: 'ligocki.a@gmail.com',
  github: 'https://github.com/adamek727',
  linkedin: 'https://www.linkedin.com/in/adamligocki',
  scholar: 'https://scholar.google.com/citations?user=jKSGGB8AAAAJ',
  repo: 'https://github.com/adamek727/adam-ligocki-web',
  goatcounterCode: 'REPLACE_ME',
  // File name inside public/ for the portrait, e.g. 'portrait.jpg'. While it is
  // empty the hero renders a placeholder block instead of a broken image.
  portrait: '',
  // The downloadable CV in public/. Generated by scripts/build_cv.py in the
  // adam-freelance repository and copied here; regenerate there and copy again
  // rather than editing the PDF.
  //
  // This is the "slate" theme: two columns, one page, made to be read by a
  // person. The "linear" theme is the single-column one Adam sends into
  // application forms, because a two-column PDF extracts as scrambled text.
  cvFile: 'adam-ligocki-cv.pdf',
} as const;
